# Generated by Django 3.2 on 2021-04-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Project_name', models.CharField(max_length=100)),
                ('Role', models.CharField(max_length=100)),
                ('Duration', models.CharField(max_length=100)),
                ('Completion_percent', models.IntegerField()),
                ('Deadline', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'ProjectLogs',
            },
        ),
    ]
