# Generated by Django 3.2 on 2021-04-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpResource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_id', models.IntegerField()),
                ('casual_leave', models.IntegerField()),
                ('total_leave', models.IntegerField()),
                ('medical_leave', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'EmpResource',
                'managed': True,
            },
        ),
    ]
